### PR TITLE
Merge to the last Skeleton updates, adapt it to your code

### PR DESCRIPTION
**Pull request by julien-boudry**
May require a new `composer update`

- Add command-line support
- Use test `composer test` for the random_test via PHPUnit testing framework. It's also an example for further tests.
- Refactoring registering methods (a unique function for all calls)
- Improve IDE support (clarify that we use Contest class)

### CODE REVIEW

**Comment by LiamM32** [comment]
I've never done a merge of this nature before. How do I do it?

Would I type ’git merge f003b91’? Would it then insert all these lines which I can then delete?

**Comment by julien-boudry** [comment]
There is no conflicts. Just use the merge button on Github. Then, on your local environment, make a `git pull`, and that's it. (and maybe a `composer update`.

You can go back at any moment with `git reset --hard <COMMIT> && git push --force`, but everything is tested. You can check on diff log (easily available on this Github PR), I don't remove anything of you.

**Comment by LiamM32** [comment]
I just reviewed the differences. They mostly look good. But I must ask; what's the benefit of deleting random-test.php and adding randomTest.php, aside from that the former doesn't work? Is this the minimum change required to make it work?

**Comment by julien-boudry** [comment]
No, it's not mandatory. But it's better for the development convention to use a Framform (PHPUnit or PestPHP), it's like a standard and it's more powerful for you. You just have to type `composer test`, and every test will run, with error formatting etc.
You will need to write other tests, to ensure the quality of your implementation.

If you prefer, I revert the change on this file, tell me.

**Comment by LiamM32** [comment]
I can try it first. But I don't think I would run this particular test as part of a batch. I would run it on it's own. It's supposed to have an output similar to main.php.

**Comment by julien-boudry** [comment]
Off course, the test is like a template, to build others later.

Very strange about the `bin/`, I don't understand too.

**Comment by LiamM32** [comment]
Now I see. It's because I was on the master branch. Your new stuff is in the `skeleton_update` branch.

**Comment by LiamM32** [comment]
I have tried it now. While some of these changes are appreciated, I'm hesitant to merge it to master because of two things. One is `bin/CondorcetCommandLine.php`. It doesn't make sense to try to run this program using the same terminal interface as Condorcet.

The other thing is RandomTest.php. I appreciate that this one actually works, unlike the one I had. But this isn't the way I would want to run it. I would rather just have a `.php` file I can run with a parameter. I think this approach to testing makes sense for finer details of a program. Just not this particular test. Though I may use the one you wrote as a reference for writing future tests.

**Comment by julien-boudry** [comment]
I have push a new commit restoring the original random_test, keeping a test example. I let you remove the command line program if not needed.

**Comment by LiamM32** [comment]
I'm going to do this. I'm just not sure about the 3 merge options, though I'm leaning towards a squash merge.

**Comment by LiamM32** [comment]
I don't know why it's showing those commits from me. 'e5f63f0' is not for the master branch. As for '9692500', I don't even know what that is. Unless if they happened accidentally when I was trying to pull these updates onto my local repository. But I didn't push anything.

**Comment by LiamM32** [comment]
I merged this, then reverted it, are some commits I accidentally added here that shouldn't be on the master branch. But I will definitely merge this if you do the following.
`git push origin +e5f63f0bdca2f3158bdb0e0a8510e6d2df235e00^:skeleton_update`
It looks like you may have to do the merge request again though.

**Comment by LiamM32** [comment]
Yeah. I deleted that commit. Perhaps I should have just issued a commit to reverse that commit just so you can see what happen.

Is there any problem you see besides the latest commit being a day old? Were there any bad consequences to this?

**Comment by LiamM32** [comment]
Well then, I suppose you're not going to do the command I wrote above. Too bad that there isn't any good way to get rid of it, as I would prefer to never be reminded of it again.

I am not very good at git, so I frequently make mistakes and scramble to find a way to revert them, and erase any evidence that they ever happened.

Are you having problems with this repository? Is there anything that you recommend I do now?

**Comment by julien-boudry** [comment]
No problem, all this project is a good practical case to learn ;-)

Let's continue on PR #9

**Pull request merged**
